version: '3.3'
services:
  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - .:/server

  django:
    build: ./server
    tty: true
    command: invoke run
    env_file:
      - .env
    volumes:
      - ./server:/server
    working_dir: /server
    ports:
      - 9000:9000
    depends_on:
      - db

  react:
    image: node:10.15.0
    volumes:
      - ./client:/client
    working_dir: /client
    ports:
      - 3000:3000
    command: /bin/bash -c "npm install && npm start"

